# DigitalOcean App Platform Configuration
# For more info: https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: labs
region: nyc
static_sites:
  - name: labs-site
    # Update 'repo' below if you fork this repository to your own account
    github:
      repo: chaddytwiceover/LABS
      branch: main
      deploy_on_push: true
    source_dir: /
    output_dir: /
    index_document: index.html
    error_document: index.html
    catchall_document: index.html
