name: labs
region: nyc
static_sites:
  - name: labs-site
    github:
      repo: chaddytwiceover/LABS
      branch: main
      deploy_on_push: true
    source_dir: /
    output_dir: /
    index_document: index.html
    error_document: index.html
    catchall_document: index.html
